<?php
/**
 * Copyright © 2013-2017 GiaPhuGroup Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \PHPCuong\ProductQuestionAndAnswer\Block\Customer\ListCustomer $block */
?>
<?php if ($block->getQuestions() && count($block->getQuestions())): ?>
    <div class="table-wrapper questions">
        <table class="data table table-questions" id="my-questions-table">
            <thead>
                <tr>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Created') ?></th>
                    <th scope="col" class="col item"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                    <th scope="col" class="col description"><?php /* @escapeNotVerified */ echo __('Question') ?></th>
                    <th scope="col" class="col actions"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getQuestions() as $question): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Created')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->dateFormat($question->getQuestionCreatedAt()); ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Product Name')) ?>" class="col item">
                        <strong class="product-name">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($question->getEntityPkValue()); ?>"><?php echo $block->escapeHtml($question->getProductName()); ?></a>
                        </strong>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Question')) ?>" class="col description question-list">
                        <?php echo $block->escapeHtml(nl2br($question->getQuestionDetail())); ?>
                        <h4><?php echo __('Answers'); ?>: </h4>
                        <?php if (!empty($answers = $block->getAnswerList($question->getQuestionId()))): ?>
                            <ul class="parent">
                            <?php foreach ($answers as $answer): ?>
                                <?php $like = ($answer['likes'] > 0) ? $answer['likes'] : ''; ?>
                                <?php $dislike = ($answer['dislikes'] > 0) ? $answer['dislikes'] : ''; ?>
                                <li>
                                    <p class="table">
                                        <span class="first-character"><?php echo $answer['first_character'];?></span>
                                        <span class="author-name">
                                            <strong><?php echo $answer['author_name'];?></strong>
                                            <small class="time"><?php echo __('Answered by'); ?> <?php echo $answer['answered_by'];?> <?php echo __('on'); ?> <?php echo $answer['created_at'];?></small>
                                        </span>
                                    </p>
                                    <p><?php echo strip_tags($answer['content'], '<br/><br /><br>');?></p>
                                    <ul class="reply" comment-id="<?php echo $answer['id']; ?>">
                                        <li title="<?php echo __('Like'); ?>" like-on="answer" class="like" clicked="false" is="like">
                                            <span>
                                                <span class="number">
                                                    <?php echo $like;?>
                                                </span>
                                                <?php echo __('Like'); ?>
                                            </span>
                                        </li>
                                        <li title="<?php echo __('Dislike'); ?>" dislike-on="answer" class="dislike" clicked="false" is="dislike">
                                            <span>
                                                <span class="number">
                                                    <?php echo $dislike;?>
                                                </span>
                                                <?php echo __('Dislike'); ?>
                                            </span>
                                        </li>
                                    </ul>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <ul>
                                <li><?php echo __('Our administrator will reply your question soon.'); ?></li>
                            </ul>
                        <?php endif; ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col actions">
                        <?php echo $this->helper('PHPCuong\ProductQuestionAndAnswer\Helper\Data')->getStatusText($question->getQuestionStatusId()); ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?php echo $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
    <div id="likes-dislikes"></div>
    <script type="text/x-magento-init">
        {
            "#likes-dislikes": {
                "PHPCuong_ProductQuestionAndAnswer/js/process-like-dislike": {
                    "likeDislikeUrl": "<?php /* @escapeNotVerified */ echo $block->getLikeDislikeUrl();?>",
                    "loadingNumberImage": "<?php echo $block->getViewFileUrl('PHPCuong_ProductQuestionAndAnswer::images/loading-number.gif'); ?>"
                }
            }
        }
    </script>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have submitted no questions.') ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?php /* @escapeNotVerified */ echo __('Back') ?></span>
        </a>
    </div>
</div>
